### PR TITLE
v0.8.2 MILESTONE RELEASE FIXES

### PR DESCRIPTION
**Pull request by rafaeldtinoco**
Replacing: https://github.com/aquasecurity/tracee/pull/2095

with a few agreed changes.

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Im fixing some makefile issues related to includes.

**Comment by rafaeldtinoco** [comment]
@grantseltzer the test isn't passing because the change you made to OSInfo removed:

image

the interface used by the test to mock the private type:

image

Also, in libbpfgo, I believe you missed to update the function description (it does not return -1, 0 or 1 anymore):

image

but that is "nit". We can either do a dirty fix and maintain the test like it is (doing a mock) or do the full fix and change the test.

**Comment by rafaeldtinoco** [comment]
I have closed that PR and removed the OSInfo "fix" commit in this PR. I have also included some other commits needed here (Makefile fix and stick with go 1.17). I believe the OSInfo change is the only think keeping us from bumping to new libbpfgo.

**Comment by rafaeldtinoco** [comment]
CentOS 8 is still with some problems AND my manjaro:

```
[rafaeldtinoco@rugged ~/.../ebpf/tracee]$ sudo ./dist/tracee-ebpf -o format:json -o option:parse-arguments --trace comm=bash --trace follow --caps cancel-drop
libbpf: failed to get EHDR from /proc/config.gz
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffff05f pc=0x7ffbd6f31141]
```
has some issue I need to investigate.

**Comment by rafaeldtinoco** [comment]
CentOS 8 issues:

image

for json printer.

**Comment by rafaeldtinoco** [comment]
There is some change to libbpf that causes it not to be able to read /proc/config.gz anymore (which is the only kconfig file available in MANJARO/ARCHLINUX):

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
fedeba74b7ca44ffcdbad7eaf7673337b0b277d5
0eb12dca7e1927d846804f0662fce9e000283f7f
bf51e3c336287bb864097e170612aaaae22106cd
d8454ba8ad83514a5afc6e3d05bddb61f299d5f4
fcd1b668c6d29a6cb0d7126883a07f5eec6aadde
62e8af46d2c269300f1e9e019ef717b283bd808a
ec3bbc05c0f23ae56e3be7dd9dcfdf4bbde10e91
d32e7ea95276b081945a09c36919b21558395e98
f009af788948ea7d422337abfb49b34d5301d341
6abeb4203d0f1f8a5dd2bf09939ce2c55846acb3
9bdb296ec6b508805e629a07c4a08778ec7ae947
25ba0076819e2c26ee5d3820ca2e2070f535d19c
e28a540c59ed0a96a50918696c7123e4adeacb17
e8802d6319ab485229d501e429bd3e1ee01e8d15
f9f7f2d30ae73b0197e1a5ba65cdf7a4bb2e91e8
812a95fdf700a52be7bf6b0ef85c316e76ea0999
9476dce6fe905a6bf1d4c483f7b2b8575c4ffb2d
8ee1202ff4e3debf9fbd2f08a778023c9eb35f30
f42d136c1ca52e4da8babea3639954d7bd5a76c0
b78c75fcb347b06c31996860353f40087ed02f48
We cannot bisect more!

Some commit in this list makes libbpf v1.0 to brake:

```
$ sudo ./dist/tracee-ebpf --install-path /tmp/tracee --cache cache-type=mem --cache mem-cache-size=512 --output format:json --output option:parse-arguments --output option:detect-syscall --trace container=new --trace event=$(./dist/tracee-rules --rules TRC-2 --list-events)
libbpf: failed to get EHDR from /proc/config.gz
fatal error: unexpected signal during runtime execution
```

**Comment by rafaeldtinoco** [comment]
I'm still missing the CENTOS8 issue (need to investigate) and the KCONFIG issue (when there is only /proc/config.gz file available).

**Comment by rafaeldtinoco** [comment]
RHEL8 is failing because there is a "equal" word (debug leftover) in libbpfgo:

image

I believe it only happens in certain kernel versions (thus the reason why it fails in RHEL8 only). Checking...

**Comment by rafaeldtinoco** [comment]
Errors happening in RHEL8:

INFO: = TEST: TRC-2 =================================================
INFO: 
2022/09/04 03:56:52 failed loading CEL signatures: failed loading configs: failed walking dir /home/rafaeldtinoco/work/ebpf/tracee/dist/rules: lstat /home/rafaeldtinoco/work/ebpf/tracee/dist/rules: permission denied
2022/09/04 03:56:52 failed loading CEL signatures: failed loading configs: failed walking dir /home/rafaeldtinoco/work/ebpf/tracee/dist/rules: lstat /home/rafaeldtinoco/work/ebpf/tracee/dist/rules: permission denied
INFO: 
INFO: TRC-2: FAILED. ERRORS:
INFO: 
2022/09/04 03:56:52 invalid operator and/or values given to filter: =
INFO: 
INFO: ALL TESTS: FAILED: TRC-2

**Comment by rafaeldtinoco** [comment]
I'm merging this as we need to test new libbpfgo for 1 week (for the v0.8.2 milestone) at least.

**Comment by grantseltzer** [comment]
> There is some change to libbpf that causes it not to be able to read /proc/config.gz anymore (which is the only kconfig file available in MANJARO/ARCHLINUX):
> 
> There are only 'skip'ped commits left to test. The first bad commit could be any of: fedeba74b7ca44ffcdbad7eaf7673337b0b277d5 0eb12dca7e1927d846804f0662fce9e000283f7f bf51e3c336287bb864097e170612aaaae22106cd d8454ba8ad83514a5afc6e3d05bddb61f299d5f4 fcd1b668c6d29a6cb0d7126883a07f5eec6aadde 62e8af46d2c269300f1e9e019ef717b283bd808a ec3bbc05c0f23ae56e3be7dd9dcfdf4bbde10e91 d32e7ea95276b081945a09c36919b21558395e98 f009af788948ea7d422337abfb49b34d5301d341 6abeb4203d0f1f8a5dd2bf09939ce2c55846acb3 9bdb296ec6b508805e629a07c4a08778ec7ae947 25ba0076819e2c26ee5d3820ca2e2070f535d19c e28a540c59ed0a96a50918696c7123e4adeacb17 e8802d6319ab485229d501e429bd3e1ee01e8d15 f9f7f2d30ae73b0197e1a5ba65cdf7a4bb2e91e8 812a95fdf700a52be7bf6b0ef85c316e76ea0999 9476dce6fe905a6bf1d4c483f7b2b8575c4ffb2d 8ee1202ff4e3debf9fbd2f08a778023c9eb35f30 f42d136c1ca52e4da8babea3639954d7bd5a76c0 b78c75fcb347b06c31996860353f40087ed02f48 We cannot bisect more!
> 
> Some commit in this list makes libbpf v1.0 to brake compilation AND the same, or another, makes this error to happen:
> 
> ```
> $ sudo ./dist/tracee-ebpf --install-path /tmp/tracee --cache cache-type=mem --cache mem-cache-size=512 --output format:json --output option:parse-arguments --output option:detect-syscall --trace container=new --trace event=$(./dist/tracee-rules --rules TRC-2 --list-events)
> libbpf: failed to get EHDR from /proc/config.gz
> fatal error: unexpected signal during runtime execution
> ```

The offending commit (at least for compilation error) is 8ee1202ff4e3debf9fbd2f08a778023c9eb35f30 which removes xsk.{c,h} from libbpf. Strange because the makefile wasn't updated? Looking into fix now. Git bisect is the coolest thing ever.
