### ISSUE TITLE
Build of non-core bpf object fails on kernels < 5.8

### ISSUE THREAD

**Issue by yanivagman** [aquasecurity/tracee#1659]
On main branch, tracee non-core bpf object doesn't compile with kernels before 5.8:
 `error: use of undeclared identifier 'PIPE_BUF_FLAG_CAN_MERGE' if ((out_pipe_last_buffer_flags & PIPE_BUF_FLAG_CAN_MERGE) == 0) {
...`

**Comment by rafaeldtinoco** [comment]
Unfortunately the way I developed https://github.com/aquasecurity/tracee-test-kernels/tree/main/tester won't allow me to do a non CO-RE compilation to each supported (there) kernel. I'll have to think of something if we don't want to drop non CO-RE support (discussed at: https://github.com/aquasecurity/tracee/issues/1651, related to "burden").
