### PR TITLE
bugfix: support dirty_pipe_splice in unexploited kernels

### LINKED ISSUE #1659: Build of non-core bpf object fails on kernels < 5.8
On main branch, tracee non-core bpf object doesn't compile with kernels before 5.8:
 `error: use of undeclared identifier 'PIPE_BUF_FLAG_CAN_MERGE' if ((out_pipe_last_buffer_flags & PIPE_BUF_FLAG_CAN_MERGE) == 0) {
...`

### LINKED ISSUE #1691: do_splice eBPF program is not affected by filters
## Prerequisites

- [ ] This affects latest released version.
- [x] This affects current development tree (origin/HEAD).
- [ ] There isn't an issue describing the bug.
- [x] I'm going to create a PR to solve this (assign to yourself).
- [ ] Someone else should solve this.

## Bug description

The `do_splice` eBPF program does not check if it should be traced, but if it should be submitted.
This means that filters won't work on the event.

### PR DESCRIPTION
**Pull request by AlonZivony**
Event implementation uses a symbol which was introduced only in kernel version 5.8.
Fixed the bug using it and a bug of using the `get_symbol_addr` helper (global values are not supported in older kernels),
Also prevent event analyzing if splice failed, just to reduce overhead and wrong analyze of kernel's data.

This PR has a problem that old Manajro kernels don't have the `do_splice` symbol for some reason in `kallsyms` file, which make the event unloadable in these versions. Ubuntu 4.18 was fine though. I don't see a way to bypass it so it will be suffice for now.

fix #1659 
fix #1691

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
> This PR has a problem that old Manajro kernels don't have the `do_splice` symbol for some reason in `kallsyms` file, which make the event unloadable in these versions. Ubuntu 4.18 was fine though. I don't see a way to bypass it so it will be suffice for now.

I find it hard that do_splice was optimized as inline (because of its size).

That leads me to think what if functions are optimized and symbols don't exist. This would be similar to the probe not existing (and not making tracee to fail when loading eBPF programs).

Also, related to do_splice, I couldn't find a kconfig to opt out of it. That is weird. It is defined as a syscall and implemented in linux/fs/splice.c without any opt outs.

**Comment by AlonZivony** [comment]
> I find it hard that do_splice was optimized as inline (because of its size).

I find it hard to believe myself. Unfortunately it really is missing from my `kallsyms` file, I don't have a concrete explanation to it.
Because it is not an exported function maybe it is possible for it to go missing in some kernel compilation.

**Comment by yanivagman** [comment]
I think that instead of adding this ZONE stuff for kernel version detection, we should handle it in userspace code and just not load the probe if the kernel < 5.8 (this will also solve the problem you might have with old manjaro versions)

**Comment by AlonZivony** [comment]
I agree with you, though it is hard to do it currently.
I think the right thing to do is when we support not loading a program we will add a dependency of kernel version to check if it is supported in the version or not.
I can add the dependency now for the event but the support for the not loading part in user-mode is out of scope for this PR IMO.

**Comment by yanivagman** [comment]
> I agree with you, though it is hard to do it currently. I think the right thing to do is when we support not loading a program we will add a dependency of kernel version to check if it is supported in the version or not. I can add the dependency now for the event but the support for the not loading part in user-mode is out of scope for this PR IMO.

Yes, I agree. Then we can wait for #1657 to be merged, on which @NDStrahilevitz will rebase and add the ability of not loading an event's programs when something fails. After that, adding a kernel version dependency to an event should be straight forward as we already have the "dependencies" field for each event where we can add the kernel version, and we also extract the running kernel version on tracee start, and pass it as part of the configuration.

**Comment by AlonZivony** [comment]
@yanivagman I think for now we should merge this PR so Tracee will be stable until the dependency PRs are merged.
If you have an issue with it please tell me.

**Comment by rafaeldtinoco** [comment]
> @yanivagman I think for now we should merge this PR so Tracee will be stable until the dependency PRs are merged. If you have an issue with it please tell me.

I agree with @AlonZivony. We should merge this instead of holding a feature focusing on specific distro (manjaro) older kernels. This is the type of burden I mentioned at https://github.com/aquasecurity/tracee/issues/1651#issuecomment-1099058753.

**Comment by yanivagman** [comment]
IMO we shouldn't merge this hacky way (using high_zoneidx) of finding the kernel version as adding kernel version event dependency is just around the corner (within days).
If you want to merge this and remove it once the new mechanism is here, go ahead

**Comment by rafaeldtinoco** [comment]
> IMO we shouldn't merge this hacky way (using high_zoneidx) of finding the kernel version as adding kernel version event dependency is just around the corner (within days).

File: pkg/ebpf/c/tracee.bpf.c [hunk 1]
```diff
@@ -4734,6 +4735,27 @@ TRACE_ENT_FUNC(do_splice, DIRTY_PIPE_SPLICE);
...
+    return 0;
+    #else
+    #ifdef CORE
+    // Check if field of struct exist to determine kernel version - some fields
+    // change between versions.
+    // In version 5.8 of the kernel, the field "high_zoneidx" changed its name to "highest_zoneidx".
+    // This means that the existence of the field "high_zoneidx" can indicate that the kernel version is lower
+    // than v5.8
+    struct alloc_context *check_508;
+    if (bpf_core_field_exists(check_508->high_zoneidx)) {
```
Comment (rafaeldtinoco) [inline pkg/ebpf/c/tracee.bpf.c:4754]: @yanivagman I agree with you this is "hacky". If you think we can wait until the "per event" support I'm okay. Please also, take a look at recent merges using the same technique (this goes together with that older discussion os us about not being able to branch condition kconfig relocations, thus the use of this "technique"). Maybe we should revisit those as well.

**Comment by rafaeldtinoco** [comment]
@AlonZivony PR: #1657 has been merged now and I believe this was waiting on it. Feel free to rebase and make needed changes to use the "handle events" PR changes.

**Comment by AlonZivony** [comment]
Also fix #1691

**Comment by yanivagman** [comment]
> I'm merging this, even being a `hacky` approach. I've opened the bug: #1743 and assigned to Alon so, when we define the kernel versioning feature, in event dependencies, Alon will have to re-fix it based on that.
> 
> PS: It is better to have a hacky fix than a broken test =D

Yes, I agree. It took longer than I thought
